# Generated by Django 3.2.9 on 2022-07-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('phone_number', models.IntegerField(verbose_name='Телефонный номер')),
                ('reserve_phone_number', models.IntegerField(blank=True, verbose_name='Запасной телефонный номер')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес проживания')),
                ('passport_image_first', models.ImageField(upload_to='documents/', verbose_name='Фото лицевой стороны паспорта')),
                ('passport_image_second', models.ImageField(upload_to='documents/', verbose_name='Фото задней стороны паспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Размер долга')),
                ('amount_meat', models.SmallIntegerField(verbose_name='Количество мяса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Должник')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
            },
        ),
    ]
