# Generated by Django 3.2.9 on 2022-07-13 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
