# Generated by Django 3.2.9 on 2022-07-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20220713_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Не оплачен'), ('Partially Paid', 'Частично оплачен'), ('Paid', 'Оплачен'), ('Expired', 'Просрочен')], default=('Not Paid', 'Не оплачен'), max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата выдачи'),
        ),
    ]
