# Generated by Django 3.2.9 on 2022-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20220715_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='progress',
            field=models.SmallIntegerField(default=0, verbose_name='Прогресс оплаты'),
        ),
    ]
