# Generated by Django 3.2.9 on 2022-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reserve_phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запасной телефонный номер'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Частично оплачен', 'Частично оплачен'), ('Оплачен', 'Оплачен'), ('Просрочен', 'Просрочен')], default='Не оплачен', max_length=40, verbose_name='Статус'),
        ),
    ]
