# Generated by Django 3.2.9 on 2022-07-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_debt_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='crm.client', verbose_name='Должник'),
        ),
    ]
