# Generated by Django 3.2.9 on 2022-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_debt_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Просрочен?'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Не оплачен'), ('Paid', 'Оплачен')], default=('Not paid', 'Не оплачен'), max_length=40, verbose_name='Статус'),
        ),
    ]
