# Generated by Django 3.2.9 on 2022-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('not Paid', 'Не оплачен'), ('paid', 'Оплачен')], default='not Paid', max_length=40, verbose_name='Статус'),
        ),
    ]
