# Generated by Django 3.2.9 on 2022-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('not paid', 'Не оплачен'), ('paid', 'Оплачен')], default='not paid', max_length=40, verbose_name='Статус'),
        ),
    ]
