# Generated by Django 3.2.9 on 2022-07-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=15, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reserve_phone_number',
            field=models.IntegerField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Запасной телефонный номер'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Действие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.client')),
            ],
        ),
    ]
