# Generated by Django 3.2.9 on 2022-07-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20220724_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='client',
        ),
        migrations.AddField(
            model_name='log',
            name='debt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.debt'),
            preserve_default=False,
        ),
    ]
