# Generated by Django 3.2.9 on 2022-07-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20220724_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
