# Generated by Django 3.2.9 on 2022-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_log_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount_meat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество мяса'),
        ),
    ]
