# Generated by Django 3.2.9 on 2022-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_debt_amount_meat'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='updater',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
